# Generated by Django 3.0.1 on 2019-12-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20191221_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='preparation_time',
            field=models.IntegerField(),
        ),
    ]
