# Generated by Django 3.0.1 on 2019-12-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20191222_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
