# Generated by Django 3.0.1 on 2019-12-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_step_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
